In [1]:
import statistics as stats

In [4]:
student_grades = [79, 87, 99, 96, 88, 79, 75, 68, 90, 91, 67]

In [5]:
stats.mean(student_grades)

83.54545454545455

In [6]:
student_grades = [79, 87, 99, 96, 88, 79, 75, 68, 90, 91, 67]

In [7]:
import numpy as np
np.sort(student_grades)

array([67, 68, 75, 79, 79, 87, 88, 90, 91, 96, 99])

In [8]:
len(student_grades)

11

In [9]:
stats.median(student_grades)

87

In [10]:
student_grades = [79, 87, 99, 96, 88, 79, 75, 68, 90, 91] 

In [11]:
np.sort(student_grades)

array([68, 75, 79, 79, 87, 88, 90, 91, 96, 99])

In [12]:
len(student_grades)

10

In [13]:
stats.median(student_grades)

87.5

In [14]:
student_grades = [79, 87, 99, 96, 88, 79, 75, 68, 90, 91] 

In [15]:
stats.mode(student_grades)

79

In [16]:
student_grades = [87, 87, 99, 99, 96, 88, 79, 75, 68, 90, 91] 

In [17]:
stats.mode(student_grades)

87

In [21]:
counts_dict = {}
for item in student_grades:
    count_of_item = student_grades.count(item)
    counts_dict[item] = count_of_item
    
print(counts_dict)

{87: 2, 99: 2, 96: 1, 88: 1, 79: 1, 75: 1, 68: 1, 90: 1, 91: 1}


In [23]:
values = counts_dict.values()
print("Values of counts in the dictionary are: ", values)

max_value = max(values)
print("Max vlaue in the counts is:", max_value)

Values of counts in the dictionary are:  dict_values([2, 2, 1, 1, 1, 1, 1, 1, 1])
Max vlaue in the counts is: 2


In [27]:
x = {'key1': 100, 'key2': 200 , 'key3':300}
for key, value in x.items():
    print("For key: ", key, "- the value is: ", value)

For key:  key1 - the value is:  100
For key:  key2 - the value is:  200
For key:  key3 - the value is:  300


In [29]:
for key, value in counts_dict.items():
    if value == max_value:
        print("Mode: ", key)

Mode:  87
Mode:  99


# Exercise

1.1

False

1.2

In [45]:
data = [4, 7, 5, 9, 8, 6, 7, 7, 8, 5, 6, 9, 8, 5, 8, 7, 4, 7, 3, 6, 8, 9, 7, 6, 9]

In [48]:
np.sort(data)

array([3, 4, 4, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9,
       9, 9, 9])

In [72]:
range = min(data), max(data)

In [73]:
print ("Range =", (range))
print ("Mean =", stats.mean(data))
print ("Median =", stats.median(data))
print ("Mode = ", stats.mode(data))

Range = (3, 9)
Mean = 6.72
Median = 7
Mode =  7


1.3

Median

1.4

You take the average of the two middle numbers

1.5

Outliers are values that are very far from the majority values in the data set. The mean is the most sensitive to outliers.